objects_tracker_node:
  ros__parameters:
    target_frame: odom
    # TODO move these params to cluster namespace
    cluster_neighbor_radius: 0.5
    cluster_min_points: 3
    visualize: true

    enable_static_bg_subtraction: true
    static_bg_subtractor:
      resolution: 0.05
      # With threshold = 0.7, scan freq = 10 Hz
      # Let it take 10 seconds to adapt to a new static object -> 0.7/(10*10) = 0.007
      # Let it take 10 seconds to forget a removed static object -> (1-0.7)/(10*10) = 0.003
      hit_increment: 0.007
      miss_decrement: 0.003
      threshold: 0.7
      publish_grid: true
      publish_filtered_pcl: true
      grid_half_size: 20.0
      inflation_radius: 1

    lmb_tracker:
      max_dt: 1.0
      gate_threshold: 6.0
      birth_existence_prob: 0.005
      death_existence_prob: 0.05
      survival_prob: 0.9999
      detection_prob: 0.04

    kalman_filter:
      pos_uncertainty: 0.2
      vel_uncertainty: 0.4
      acc_uncertainty: 1.0
